## En este archivo se utilizarán las funciones de usethis
## para modificar la estructura del paquete

usethis::use_testthat(3)

#Guanajuato
usethis::use_data_raw("bdos_gto_locales")
usethis::use_data_raw("bdos_gto_auxiliares")
usethis::use_data_raw("bdos_gto_locales")
usethis::use_data_raw("bdos_gto_auxiliares")
usethis::use_data_raw("bdos_pue_locales")
usethis::use_data_raw("bdos_pue_auxiliares")
usethis::use_data_raw("catalogo")
usethis::use_data_raw("bdos_cdmx_locales")
usethis::use_data_raw("bdos_cdmx_auxiliares")
usethis::use_data_raw("bdos_mor_locales")
usethis::use_data_raw("bdos_mor_auxiliares")
usethis::use_data_raw("bdos_ver_locales")
usethis::use_data_raw("bdos_ver_auxiliares")
usethis::use_data_raw("bdos_jal_locales")
usethis::use_data_raw("bdos_jal_auxiliares")
usethis::use_data_raw("resultados")
usethis::use_data_raw("paleta")
usethis::use_data_raw("nombres_elecciones")
usethis::use_data_raw("claves")
usethis::use_data_raw("modificacion_censo")
usethis::use_test("estructura")
usethis::use_test("analisis_explorar")
usethis::use_test("ags")
usethis::use_test("cdmx")
usethis::use_test("chis")
usethis::use_test("coah")
usethis::use_test("dgo")
usethis::use_test("gto")
usethis::use_test("hgo")
usethis::use_test("jal")
usethis::use_test("mex")
usethis::use_test("mor")
usethis::use_test("oaxaca")
usethis::use_test("pue")
usethis::use_test("q_roo")
usethis::use_test("tamps")
usethis::use_test("ver")
usethis::use_vignette("flujo_electoral")
usethis::use_vignette("flujo_tablero")
usethis::use_package("stratification")
usethis::use_package("ggsflabel")
usethis::use_r("visualizaciones")
