---
title: "Documentación"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción

Este es un documento para describir de manera interna las bases de datos electorales contenidas en el paquete y algunas de sus particularidades.

## Parámetros generales

Las bases de datos contienen variables de tipo caracter para todas sus variables no electorales, y de tipo de tipo numérica para todas las variables electorales.

Los nombres de las bases de datos electorales nacionales se componen de la siguiente manera: "nac_EE_AA". Eto corresponde a 3 dígitos que indican que es nacional, dos dígitos de la elección y dos dígitos del año.

Los nombres de las bases de datos locales se componen de la siguiente manera: "EEEE_EE_AA",
los primeros 3 o 4 dígitos son la abreviatura oficial del estado, los siguientes 2 del tipo de elección y los últimos dos, del año.

Las bases de datos en su formato inicial tienen como unidad básica de observación la casilla y cada una de estas observaciones tiene un identificador llamado "clave_casilla", el cual está compuesto de la siguiente manera:  EESSSSTCCXX, es decir, dos dígitos de estado, cuatro de sección, tipo de casilla, clave de casilla, clave de casilla contigua en casillas extraordinarias. NOTA: si la casilla no es extraordinaria, XX siempre va a ser 00.

Los tipos de casilla son los siguientes: B = Básica, C = Contigua, E = Extraordinaria, S = Especial, P = Prisión preventiva (en este último caso, la sección es 9999).

Cada base de datos tiene una otra base en la que se indican las alizan que hubieron dependiendo del nivel de la elección, por ejemplo, si es de Ayuntamientos, la unidad de alianzas son los municipios; si es de diputados, es el distrito.Las bases de datos de alianzas comparten el mismo nombre que el que la base de datos electoral que le corresponde más el prefijo "alianzas_".

# Bases de datos nacionales

## Presidente 

### nac_pr_18.rda

## Diputado 
Para indicar si las casillas son de mayoría relativa o de representación proporcional, se creó la variable "mr_rp".

### nac_df_21.rda
En los resultados generales que publica el INE no se toma en cuenta las casillas especiales, y por ello puede que esos resultados no coincidan.

### nac_df_18.rda
En ele_df_2018 para saber cuál casilla era mr y cuál rp la variable num_acta_impreso tiene valores 6, 7 y 8. 7 y 8 eran especiales por lo que alguno de estos dos números significaba mr y otro rp. Los computos del ine reportan los resultados de las especiales con num acta impreso = 7. Asumiendo que el ine reporta los resultados de mayoria relativa, asumimos que 7 = mr y 8 = pr.

En los resultados generales que publica el INE no se toma en cuenta las casillas especiales, y por ello puede que esos resultados no coincidan.

### nac_df_15.rda

Para df_15 el LEEME dice que en tipo de acta 3 = mr en casillas especiales, 4 = rp en casillas especiales y 2 = mr en el resto de casillas. Sin embargo, tienen registros de tipo de acta 3 con todo los tipos de casillas, es decir tienen tipo de acta 3 con tipo de casilla B, C, E y S. También tienen 2  con casilla especial (S). Así pues, al sumar las casillas especiales con tipo de acta 2 con las casillas especiales con tipo de acta 3, da iguala al número de casillas especiales con numero de acta 4. Por lo que se supone que hubo un error de captura y en algunos lugares pusieron tipo de acta 3 cuando no eran casillas especiales y en otros tipo de acta 2 cuando si eran casillas especiales

## Consultas populares
### nac_cp_22.rda
Esta base de datos se refiere a la consulta popular de Revocación de mandato.

Los resultado están por unidad territorial la cual se indicaba con los votos por sección sede, cada sección sede concentraba los votos de las secciones que votaban en la sede, pero estos no se encuentran desglosados por sección. Para saber qué secciones componen cada unidad territorial, se le pega un catálogo de unidades territoriales.



# Bases de datos locales
## Pérdida de registro

2021: FXM, RSP, PES*

2018: PES*, PANAL

2016: PH

* El PES perdió su registro dos veces porque en 2018 lo perdió como Encuentro Social y en 2021 como Partido Encuentro Solidario.

# Aguascalientes

### inst/electoral/ags/dl_16
### inst/electoral/ags/gb_16
### inst/electoral/ags/pm_16
### inst/electoral/ags/dl_18
### inst/electoral/ags/pm_19
### inst/electoral/ags/pm_21
### inst/electoral/ags/dl_21

## Chiapas

### Partidos políticos locales:

Chiapas Unido - PCHU

Podemos mover a Chiapas - PMCH

Nueva alianza Chiapas - PANAL

Partido Popular Chiapaneco - PPCH

### inst/electoral/chis/dl_21.rda
### inst/electoral/chis/gb_18.rda
### inst/electoral/chis/chis_pm_18.rda
pm_18_chis contiene extraordinaria 18 chiapas
### inst/electoral/chis/pm_21.rda
pm_21_chis contiene extraordinaria 22 de chiapas

### Elecciones extraordinarias Chiapas

los municipios de siltepec, venustiano carranza, el parral y emiliano zapata

# Coahuila

### inst/electoral/coah/dl-17
### inst/electoral/coah/pm_17
### inst/electoral/coah/gb_17
### inst/electoral/coah/pm_18
### inst/electoral/coah/dl_20
### inst/electoral/coah/pm_21

# Durango

### inst/electoral/dgo/dl_16
### inst/electoral/dgo/gb_16
### inst/electoral/dgo/pm_16
### inst/electoral/dgo/dl_18
### inst/electoral/dgo/pm_19
### inst/electoral/dgo/dl_21

# Hidalgo

### inst/electoral/dgo/dl_16
### inst/electoral/dgo/pm_16
### inst/electoral/dgo/gb_16
### inst/electoral/dgo/dl_18
### inst/electoral/dgo/pm_20

# México

### inst/electoral/dgo/dl_15
### inst/electoral/dgo/pm_15
### inst/electoral/dgo/gb_17
### inst/electoral/dgo/dl_18
### inst/electoral/dgo/pm_18
### inst/electoral/dgo/dl_21
### inst/electoral/dgo/pm_21

# Oaxaca

### inst/electoral/dgo/dl_16
### inst/electoral/dgo/dl_18
### inst/electoral/dgo/gb_16
### inst/electoral/dgo/pm_16
### inst/electoral/dgo/pm_18

# Quintana Roo

### inst/electoral/dgo/dl_16
### inst/electoral/dgo/gb_16
### inst/electoral/dgo/pm_16
### inst/electoral/dgo/pm_18
### inst/electoral/dgo/dl_19

# Tamaulipas

### inst/electoral/dgo/dl_16
### inst/electoral/dgo/gb_16
### inst/electoral/dgo/pm_16
### inst/electoral/dgo/pm_18
### inst/electoral/dgo/dl_19
### inst/electoral/dgo/pm_21

### Bases de datos auxiliares

## Durango
Partidos políticos locales:


Partido Duranguense - PD

### gb_16.rda

### pm_16.rda

### dl_18.rda

en dl18 de durango solo hay tipo de casilla especial S1, por lo que asumimos que solo registran mr

### pm_19.rda

### dl_21.rda

en dl21 de durango la variable pan_pri_prd_total es la suma de los votos de los tres partidos y las combinaciones de alianzas entre ellos

en dl 21 de durango la variable morena_pt_total es la suma de los votos de morena, pt y morena_pt

en dl21 de durango solo hay tipo de casilla especial S1, por lo que asumimos que solo registran mr

## México

### Partidos políticos locales:

Nueva Alianza Estado de México - PANAL

dl_18.rda
dl_21.rda
gb_17.rda
pm_18.rda
pm_21.rda

pm_21_mex contiene extraordinaria 21 edomex

### mex_pmext_21.rda

Estas elecciones fueron en el municipio de Nextlalpan.

